"""phase6_marketplace_and_customer

Revision ID: 112e2205a754
Revises: e7f1a2b3c4d5
Create Date: 2026-09-19 06:25:57.471661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '112e2205a754'
down_revision: Union[str, None] = 'e7f1a2b3c4d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id'),
    sa.UniqueConstraint('user_id', name='uq_customer_user_id')
    )
    op.create_index('ix_customers_status', 'customers', ['status'], unique=False)
    op.create_index('ix_customers_user_id', 'customers', ['user_id'], unique=False)
    op.create_table('customer_addresses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=True),
    sa.Column('recipient_name', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('address_line_1', sa.String(length=255), nullable=False),
    sa.Column('address_line_2', sa.String(length=255), nullable=True),
    sa.Column('locality', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('postal_code', sa.String(length=50), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_customer_addresses_customer_id', 'customer_addresses', ['customer_id'], unique=False)
    op.create_index('ix_customer_addresses_is_default', 'customer_addresses', ['customer_id', 'is_default'], unique=False)
    op.create_table('customer_sellers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('seller_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('first_interaction_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_interaction_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['seller_id'], ['sellers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_id', 'seller_id', name='uq_customer_seller')
    )
    op.create_index('ix_customer_sellers_customer_id', 'customer_sellers', ['customer_id'], unique=False)
    op.create_index('ix_customer_sellers_seller_id', 'customer_sellers', ['seller_id'], unique=False)
    op.drop_index(op.f('ix_price_books_branch_id'), table_name='price_books')
    op.drop_index(op.f('ix_price_books_seller_id'), table_name='price_books')
    op.add_column('seller_branches', sa.Column('is_marketplace_visible', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_seller_branches_is_marketplace_visible'), 'seller_branches', ['is_marketplace_visible'], unique=False)
    op.add_column('sellers', sa.Column('marketplace_status', sa.String(length=50), nullable=False))
    op.create_index(op.f('ix_sellers_marketplace_status'), 'sellers', ['marketplace_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sellers_marketplace_status'), table_name='sellers')
    op.drop_column('sellers', 'marketplace_status')
    op.drop_index(op.f('ix_seller_branches_is_marketplace_visible'), table_name='seller_branches')
    op.drop_column('seller_branches', 'is_marketplace_visible')
    op.create_index(op.f('ix_price_books_seller_id'), 'price_books', ['seller_id'], unique=False)
    op.create_index(op.f('ix_price_books_branch_id'), 'price_books', ['branch_id'], unique=False)
    op.drop_index('ix_customer_sellers_seller_id', table_name='customer_sellers')
    op.drop_index('ix_customer_sellers_customer_id', table_name='customer_sellers')
    op.drop_table('customer_sellers')
    op.drop_index('ix_customer_addresses_is_default', table_name='customer_addresses')
    op.drop_index('ix_customer_addresses_customer_id', table_name='customer_addresses')
    op.drop_table('customer_addresses')
    op.drop_index('ix_customers_user_id', table_name='customers')
    op.drop_index('ix_customers_status', table_name='customers')
    op.drop_table('customers')
    # ### end Alembic commands ###
