"""phase2_seller_platform

Revision ID: 2010fc7ee67f
Revises: 0001_phase1
Create Date: 2026-09-18 08:30:45.434891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2010fc7ee67f'
down_revision: Union[str, None] = '0001_phase1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sellers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sellers_tenant_id'), 'sellers', ['tenant_id'], unique=True)
    op.create_table('seller_branches',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('seller_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('timezone', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['seller_id'], ['sellers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('seller_id', 'code', name='uix_seller_branch_code')
    )
    op.create_index(op.f('ix_seller_branches_seller_id'), 'seller_branches', ['seller_id'], unique=False)
    op.create_table('seller_settings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('seller_id', sa.Uuid(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('tax_rate', sa.Float(), nullable=True),
    sa.Column('business_hours', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['seller_id'], ['sellers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seller_settings_seller_id'), 'seller_settings', ['seller_id'], unique=True)
    op.create_table('seller_staff_profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('seller_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('job_title', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['seller_id'], ['sellers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('seller_id', 'user_id', name='uix_seller_staff_user')
    )
    op.create_index(op.f('ix_seller_staff_profiles_seller_id'), 'seller_staff_profiles', ['seller_id'], unique=False)
    op.create_index(op.f('ix_seller_staff_profiles_user_id'), 'seller_staff_profiles', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_seller_staff_profiles_user_id'), table_name='seller_staff_profiles')
    op.drop_index(op.f('ix_seller_staff_profiles_seller_id'), table_name='seller_staff_profiles')
    op.drop_table('seller_staff_profiles')
    op.drop_index(op.f('ix_seller_settings_seller_id'), table_name='seller_settings')
    op.drop_table('seller_settings')
    op.drop_index(op.f('ix_seller_branches_seller_id'), table_name='seller_branches')
    op.drop_table('seller_branches')
    op.drop_index(op.f('ix_sellers_tenant_id'), table_name='sellers')
    op.drop_table('sellers')
    # ### end Alembic commands ###
