"""phase3_customization_engine

Revision ID: 275f700c133f
Revises: debba6592524
Create Date: 2026-09-18 09:44:46.124410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '275f700c133f'
down_revision: Union[str, None] = 'debba6592524'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('application_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_applications_key'), 'applications', ['key'], unique=True)
    op.create_table('configuration_definitions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('domain', sa.String(length=50), nullable=False),
    sa.Column('data_type', sa.String(length=50), nullable=False),
    sa.Column('schema', sa.JSON(), nullable=True),
    sa.Column('default_value', sa.JSON(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('is_sensitive', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_configuration_definitions_key'), 'configuration_definitions', ['key'], unique=True)
    op.create_table('application_modules',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('application_id', sa.Uuid(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('application_id', 'key', name='uq_app_module_key')
    )
    op.create_index(op.f('ix_application_modules_key'), 'application_modules', ['key'], unique=False)
    op.create_table('configuration_values',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('application_id', sa.Uuid(), nullable=True),
    sa.Column('module_id', sa.Uuid(), nullable=True),
    sa.Column('definition_id', sa.Uuid(), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['definition_id'], ['configuration_definitions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['module_id'], ['application_modules.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_config_values_unique_published', 'configuration_values', ['tenant_id', 'definition_id', 'application_id', 'module_id'], unique=True, postgresql_where=sa.text("status = 'PUBLISHED'"))
    op.create_index(op.f('ix_configuration_values_application_id'), 'configuration_values', ['application_id'], unique=False)
    op.create_index(op.f('ix_configuration_values_definition_id'), 'configuration_values', ['definition_id'], unique=False)
    op.create_index(op.f('ix_configuration_values_tenant_id'), 'configuration_values', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_configuration_values_tenant_id'), table_name='configuration_values')
    op.drop_index(op.f('ix_configuration_values_definition_id'), table_name='configuration_values')
    op.drop_index(op.f('ix_configuration_values_application_id'), table_name='configuration_values')
    op.drop_index('ix_config_values_unique_published', table_name='configuration_values', postgresql_where=sa.text("status = 'PUBLISHED'"))
    op.drop_table('configuration_values')
    op.drop_index(op.f('ix_application_modules_key'), table_name='application_modules')
    op.drop_table('application_modules')
    op.drop_index(op.f('ix_configuration_definitions_key'), table_name='configuration_definitions')
    op.drop_table('configuration_definitions')
    op.drop_index(op.f('ix_applications_key'), table_name='applications')
    op.drop_table('applications')
    # ### end Alembic commands ###
