"""phase8_business_models

Revision ID: 374b262d3b61
Revises: c3d4e5f6a7b8
Create Date: 2026-09-20 10:36:31.791799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '374b262d3b61'
down_revision: Union[str, None] = 'c3d4e5f6a7b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('price_policy_versions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('service_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('recalculation_enabled', sa.Boolean(), nullable=False),
    sa.Column('price_change_policy', sa.String(length=50), nullable=False),
    sa.Column('price_rejection_policy', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service_configuration_versions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('service_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('configuration_snapshot', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('order_items', sa.Column('service_configuration_version_id', sa.Uuid(), nullable=True))
    op.add_column('order_items', sa.Column('price_policy_version_id', sa.Uuid(), nullable=True))
    op.add_column('order_items', sa.Column('applicable_rate', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('order_items', sa.Column('price_policy_snapshot', sa.JSON(), nullable=True))
    op.create_foreign_key(None, 'order_items', 'price_policy_versions', ['price_policy_version_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'order_items', 'service_configuration_versions', ['service_configuration_version_id'], ['id'], ondelete='SET NULL')
    op.add_column('orders', sa.Column('price_locked_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'price_locked_at')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.drop_column('order_items', 'price_policy_snapshot')
    op.drop_column('order_items', 'applicable_rate')
    op.drop_column('order_items', 'price_policy_version_id')
    op.drop_column('order_items', 'service_configuration_version_id')
    op.drop_table('service_configuration_versions')
    op.drop_table('price_policy_versions')
    # ### end Alembic commands ###
