"""phase2_harden_seller_foundation

Revision ID: debba6592524
Revises: 2010fc7ee67f
Create Date: 2026-09-18 08:55:46.370357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'debba6592524'
down_revision: Union[str, None] = '2010fc7ee67f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_hours',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('branch_id', sa.Uuid(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('is_open', sa.Boolean(), nullable=False),
    sa.Column('open_time', sa.Time(), nullable=True),
    sa.Column('close_time', sa.Time(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['seller_branches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('branch_id', 'day_of_week', name='uix_branch_day')
    )
    op.create_index(op.f('ix_business_hours_branch_id'), 'business_hours', ['branch_id'], unique=False)
    op.create_index(op.f('ix_business_hours_tenant_id'), 'business_hours', ['tenant_id'], unique=False)
    op.add_column('seller_branches', sa.Column('tenant_id', sa.Uuid(), nullable=False))
    op.add_column('seller_branches', sa.Column('phone', sa.String(length=50), nullable=True))
    op.add_column('seller_branches', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('seller_branches', sa.Column('address_line_1', sa.String(length=255), nullable=True))
    op.add_column('seller_branches', sa.Column('address_line_2', sa.String(length=255), nullable=True))
    op.add_column('seller_branches', sa.Column('city', sa.String(length=100), nullable=True))
    op.add_column('seller_branches', sa.Column('state', sa.String(length=100), nullable=True))
    op.add_column('seller_branches', sa.Column('postal_code', sa.String(length=50), nullable=True))
    op.add_column('seller_branches', sa.Column('country', sa.String(length=100), nullable=True))
    op.add_column('seller_branches', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('seller_branches', sa.Column('longitude', sa.Float(), nullable=True))
    op.create_index(op.f('ix_seller_branches_tenant_id'), 'seller_branches', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'seller_branches', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.drop_column('seller_branches', 'timezone')
    op.add_column('seller_settings', sa.Column('timezone', sa.String(length=100), nullable=False))
    op.add_column('seller_settings', sa.Column('locale', sa.String(length=20), nullable=False))
    op.add_column('seller_settings', sa.Column('date_format', sa.String(length=50), nullable=False))
    op.add_column('seller_settings', sa.Column('time_format', sa.String(length=50), nullable=False))
    op.drop_column('seller_settings', 'business_hours')
    op.drop_column('seller_settings', 'tax_rate')
    op.add_column('seller_staff_profiles', sa.Column('tenant_id', sa.Uuid(), nullable=False))
    op.add_column('seller_staff_profiles', sa.Column('employee_code', sa.String(length=50), nullable=True))
    op.add_column('seller_staff_profiles', sa.Column('display_name', sa.String(length=255), nullable=True))
    op.add_column('seller_staff_profiles', sa.Column('phone', sa.String(length=50), nullable=True))
    op.alter_column('seller_staff_profiles', 'seller_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(op.f('uix_seller_staff_user'), 'seller_staff_profiles', type_='unique')
    op.create_index(op.f('ix_seller_staff_profiles_tenant_id'), 'seller_staff_profiles', ['tenant_id'], unique=False)
    op.create_unique_constraint('uix_staff_tenant_user', 'seller_staff_profiles', ['tenant_id', 'user_id'])
    op.create_foreign_key(None, 'seller_staff_profiles', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.drop_column('seller_staff_profiles', 'job_title')
    op.add_column('sellers', sa.Column('business_name', sa.String(length=255), nullable=False))
    op.add_column('sellers', sa.Column('legal_name', sa.String(length=255), nullable=True))
    op.add_column('sellers', sa.Column('display_name', sa.String(length=255), nullable=True))
    op.add_column('sellers', sa.Column('slug', sa.String(length=100), nullable=False))
    op.add_column('sellers', sa.Column('description', sa.String(length=1000), nullable=True))
    op.add_column('sellers', sa.Column('business_type', sa.String(length=100), nullable=True))
    op.add_column('sellers', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('sellers', sa.Column('phone', sa.String(length=50), nullable=True))
    op.add_column('sellers', sa.Column('website', sa.String(length=255), nullable=True))
    op.add_column('sellers', sa.Column('logo_url', sa.String(length=1000), nullable=True))
    op.create_index(op.f('ix_sellers_slug'), 'sellers', ['slug'], unique=True)
    op.drop_column('sellers', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sellers', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_sellers_slug'), table_name='sellers')
    op.drop_column('sellers', 'logo_url')
    op.drop_column('sellers', 'website')
    op.drop_column('sellers', 'phone')
    op.drop_column('sellers', 'email')
    op.drop_column('sellers', 'business_type')
    op.drop_column('sellers', 'description')
    op.drop_column('sellers', 'slug')
    op.drop_column('sellers', 'display_name')
    op.drop_column('sellers', 'legal_name')
    op.drop_column('sellers', 'business_name')
    op.add_column('seller_staff_profiles', sa.Column('job_title', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'seller_staff_profiles', type_='foreignkey')
    op.drop_constraint('uix_staff_tenant_user', 'seller_staff_profiles', type_='unique')
    op.drop_index(op.f('ix_seller_staff_profiles_tenant_id'), table_name='seller_staff_profiles')
    op.create_unique_constraint(op.f('uix_seller_staff_user'), 'seller_staff_profiles', ['seller_id', 'user_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('seller_staff_profiles', 'seller_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('seller_staff_profiles', 'phone')
    op.drop_column('seller_staff_profiles', 'display_name')
    op.drop_column('seller_staff_profiles', 'employee_code')
    op.drop_column('seller_staff_profiles', 'tenant_id')
    op.add_column('seller_settings', sa.Column('tax_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('seller_settings', sa.Column('business_hours', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('seller_settings', 'time_format')
    op.drop_column('seller_settings', 'date_format')
    op.drop_column('seller_settings', 'locale')
    op.drop_column('seller_settings', 'timezone')
    op.add_column('seller_branches', sa.Column('timezone', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'seller_branches', type_='foreignkey')
    op.drop_index(op.f('ix_seller_branches_tenant_id'), table_name='seller_branches')
    op.drop_column('seller_branches', 'longitude')
    op.drop_column('seller_branches', 'latitude')
    op.drop_column('seller_branches', 'country')
    op.drop_column('seller_branches', 'postal_code')
    op.drop_column('seller_branches', 'state')
    op.drop_column('seller_branches', 'city')
    op.drop_column('seller_branches', 'address_line_2')
    op.drop_column('seller_branches', 'address_line_1')
    op.drop_column('seller_branches', 'email')
    op.drop_column('seller_branches', 'phone')
    op.drop_column('seller_branches', 'tenant_id')
    op.drop_index(op.f('ix_business_hours_tenant_id'), table_name='business_hours')
    op.drop_index(op.f('ix_business_hours_branch_id'), table_name='business_hours')
    op.drop_table('business_hours')
    # ### end Alembic commands ###
